services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: develop
    container_name: hello-dotnet
    develop:
      watch:
        - action: rebuild
          path: ./backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000

  webserver:
    image: nginx:mainline-alpine3.20-slim
    container_name: hello-nginx
    depends_on: 
      - backend
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/share/nginx/html/static:ro

       